sudo: false

cache:
  directories:
    - $HOME/.cache/pip

language: python

python:
  - '2.7'
  # - '3.6'

env:
- PYRAMID_VER=1.4.0
- PYRAMID_VER=1.6.0
- PYRAMID_VER=1.9

install:
  - pip install -e .[dev]

script:
  - pip install "Pyramid~=${PYRAMID_VER}"
  - nosetests
  - rm -rf dist && python setup.py sdist && pip install dist/*.tar.gz
  - python setup.py check -r -s  # Check the setuptools readme
